packages:
  - directus
  - app
  - api
  - docs
  - packages/*
  - tests/*

catalog:
  '@ngneat/falso': '6.4.0'
  '@rollup/plugin-node-resolve': '15.0.2'
  '@rollup/plugin-virtual': '3.0.1'
  '@types/fs-extra': '11.0.1'
  '@types/geojson': '7946.0.10'
  '@types/inquirer': '9.0.3'
  '@types/js-yaml': '4.0.5'
  '@types/json2csv': '5.0.3'
  '@types/lodash-es': '4.17.7'
  '@types/marked': '4.0.8'
  '@types/node': '18.15.13'
  '@types/supertest': '2.0.12'
  '@types/uuid': '9.0.1'
  '@types/wellknown': '0.5.4'
  '@rollup/plugin-yaml': '4.1.2'
  '@vitejs/plugin-vue': '5.2.3'
  '@vitest/coverage-v8': '1.6.1'
  '@vue/compiler-sfc': '3.2.47'
  '@vue/test-utils': '2.4.6'
  '@wbce-d9/format-title': '10.0.0'
  '@wbce-d9/tsconfig': '2.0.0'
  axios: '^1.12.0'
  chalk: '5.2.0'
  commander: '10.0.1'
  date-fns: '2.29.3'
  execa: '7.1.1'
  express: '^4.21.2'
  fs-extra: '11.1.1'
  geojson: '0.5.0'
  inquirer: '9.1.5'
  joi: '17.9.1'
  js-yaml: '4.1.1'
  json-to-graphql-query: '2.2.5'
  json2csv: '5.0.7'
  knex: '3.1.0'
  lodash-es: '4.17.23'
  marked: '4.3.0'
  micromustache: '8.0.3'
  nanoid: '5.0.9'
  openapi3-ts: '3.2.0'
  ora: '6.3.0'
  p-queue: '7.3.4'
  pino: '8.11.0'
  rollup: '3.29.5'
  sass: '1.85.0'
  supertest: '6.3.3'
  typescript: '5.0.4'
  uuid: '9.0.0'
  vite: '6.4.1'
  vitest: '1.6.1'
  vue: '3.2.47'
  vue-router: '4.1.6'
  wellknown: '0.5.0'
  zod: '3.22.3'
