body:
  - type: markdown
    attributes:
      value: |
        Hi, thank you for taking the time to create a docs suggestion!

        Please do be aware that this is _not_ the place to ask a question. To ask a question, [join our Discord server](https://directus.chat) instead!

  - type: input
    attributes:
      label: Subject Area
      description: What topic should we create/improve documentation for?

  - type: textarea
    attributes:
      label: Suggestions
      description: Please detail exactly what you think would be a good addition to the docs.
